
server:
  port: 9527

spring:
  application:
    name: nacos-provide
    # ps add test
    #name: nacos-provide1

  cloud:
    nacos:
      discovery:
        #server-addr: 10.16.10.166
        server-addr: 127.0.0.1:8848




